# Numpy 

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,27,4], np.int8)

In [3]:
myarr

array([ 3,  6, 27,  4], dtype=int8)

In [4]:
myarr.shape

(4,)

In [5]:
myarr.dtype

dtype('int8')

# Array creation : conversion from other python structures

In [6]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [7]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [8]:
listarray.dtype

dtype('int64')

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
listarray[1,2] = 45

In [12]:
listarray

array([[ 1,  2,  3],
       [ 5,  8, 45],
       [ 0,  3,  1]])

# Array creation using objects

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,5,12)

In [18]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [19]:
emp = np.empty((4,6))

In [20]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.02360935e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 1.69121096e-306, 8.34449382e-308]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

# imp function

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr = arr.ravel()

In [29]:
arr.shape

(99,)

In [30]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [32]:
ar = np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [41]:
ar.nbytes

72

In [42]:
one = np.array([1,2,3,4,5])

In [43]:
one.argmax()

np.int64(4)

In [44]:
one.argmin()

np.int64(0)

In [47]:
one.argsort()

array([0, 1, 2, 3, 4])

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.argmin()

np.int64(8)

In [50]:
ar.argmax()

np.int64(6)

In [51]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [52]:
ar.argmax(axis=0)

array([2, 1, 1])

In [53]:
ar.argmax(axis=1)

array([2, 2, 0])

In [54]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [55]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [56]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [57]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [58]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [60]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [61]:
ar.sum()

np.int64(29)

In [62]:
ar.max()

np.int64(7)

In [63]:
ar.min()

np.int64(0)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [67]:
type(np.where(ar>5))

tuple

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [70]:
import sys

In [73]:
py_ar = [0,4,55,2]

In [75]:
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(1) * len(py_ar)

112

In [78]:
np_ar.itemsize * np_ar.size

32